esphome:
  name: makeskyblue-mppt
  friendly_name: MakeSkyBlue MPPT Controller

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source: github://pikerr/esphome-makeskyblue-uart

wifi:
  ssid: "YOUR_WIFI_SSID"
  password: "YOUR_WIFI_PASSWORD"
  ap:
    ssid: "Makeskyblue-Mppt Fallback"
    password: "password123"

api:
ota:
  - platform: esphome

logger:
  level: DEBUG

uart:
  - id: uart_makeskyblue
    tx_pin: GPIO17
    rx_pin: GPIO16
    baud_rate: 9600

makeskyblue_uart:
  id: msb
  uart_id: uart_makeskyblue
  update_interval: 2s

sensor:
  - platform: makeskyblue_uart
    makeskyblue_uart_id: msb
    battery_voltage:
      id: msb_battery_voltage
      name: "Напряжение АКБ"
    battery_current:
      id: msb_battery_current
      name: "Ток заряда АКБ"
    solar_voltage:
      id: msb_solar_voltage
      name: "Напряжение СП"
    solar_power:
      id: msb_solar_power
      name: "Мощность СП"
    temperature:
      id: msb_temperature
      name: "Температура"
    accumulated_kwh:
      id: msb_accumulated_kwh
      name: "Выработка кВт·ч"

binary_sensor:
  - platform: makeskyblue_uart
    makeskyblue_uart_id: msb
    link_connected:
      id: msb_link_connected
      name: "Связь UART"
    mppt_mode:
      id: msb_mppt_mode
      name: "Режим MPPT"

number:
  - platform: makeskyblue_uart
    makeskyblue_uart_id: msb
    bulk_voltage:
      id: msb_bulk_voltage
      name: "Задать Bulk V"
      min_value: 10.0
      max_value: 65.0
      step: 0.1
    float_voltage:
      id: msb_float_voltage
      name: "Задать Float V"
      min_value: 10.0
      max_value: 65.0
      step: 0.1
    max_charge_current:
      id: msb_max_charge_current
      name: "Задать макс. ток A"
      min_value: 0.0
      max_value: 60.0
      step: 1.0

select:
  - platform: makeskyblue_uart
    makeskyblue_uart_id: msb
    battery_type:
      id: msb_battery_type
      name: "Тип АКБ"
